### PR TITLE
Improves Sony Ci Webhook Logs interface

### LINKED ISSUE #606: BUG: the Sony Ci Webhook Log interfaces don't show anything useful
### The problem
As part of #585 I wanted to make sure we had a nice visible record of the attempts by Sony Ci to hit our AMS endpoints with webhooks. The records are being saved, but the interface is lacking in useful information, because I started with scaffolding and didn't code it out much beyond that.

**Index page - missing success/failure **
image

**show page - missing everything except a back button**
image

### Done when
1. Index page has a Success or Failure status
2. Show page shows all fields, and the serialized fields are nicely formatted for browser display.

### PR DESCRIPTION
**Pull request by afred**
* Adds fields to sony_ci_webhook_logs table:
  * GUIDs - serialized array for storing affected GUIDs that we can link to directly
    from the interface.
  * response_status - integer value of HTTP response status sent back to Sony Ci API.
* Uses presenter pattern for readying WebhookLog data for display.
* Adds useful fields to #index and #show fields and generally improves styling.
* Adds pagination.
* Removes unused stuff from original scaffolding generator.

Closes #606.

### CODE REVIEW

**Comment by afred** [comment]
# Index view
image

# Show view
image

**Comment by afred** [comment]
image

**Review by jasoncorum — APPROVED** [review]
👍

**Comment by afred** [comment]
image

**Pull request merged**
