### PR TITLE
update to latest Hyrax / Ruby version

### PR DESCRIPTION
**Pull request by orangewolf**
to move your db from mysql to postgres - `MIGRATE_DB=1 dc up pgloader`
then start the app.

### CODE REVIEW

**Review by ShanaLMoore — DISMISSED** [review]

**Comment by ShanaLMoore** [comment]
All specs are failing on 

image

👀

**Comment by ShanaLMoore** [comment]
i get the following trying to build this branch
image (32)

**Comment by ShanaLMoore** [comment]
> i get the following trying to build this branch image (32)

This was resolved by commenting out these two lines: 

https://github.com/WGBH-MLA/ams/blob/develop/Dockerfile#L69-L71

**Review by kirkkwang — APPROVED** [review]
big one!

**Pull request merged**
